# Generated by Django 3.0.4 on 2020-05-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='action',
            new_name='active',
        ),
    ]
